"""empty message

Revision ID: c11c2e94c7c7
Revises: 
Create Date: 2023-01-28 18:46:08.536711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11c2e94c7c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vcac')),
    sa.UniqueConstraint('email', name=op.f('uq_vcac_email')),
    sa.UniqueConstraint('username', name=op.f('uq_vcac_username'))
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('apply_period', sa.String(), nullable=False),
    sa.Column('apply_method', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('inquiries', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('vcac_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vcac_id'], ['vcac.id'], name=op.f('fk_program_vcac_id_vcac')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program')
    op.drop_table('vcac')
    # ### end Alembic commands ###
